/*
 * generated by Xtext 2.14.0
 */
package org.blockchain.rell.ide

import com.google.inject.Guice
import org.blockchain.rell.RellRuntimeModule
import org.blockchain.rell.RellStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RellIdeSetup extends RellStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RellRuntimeModule, new RellIdeModule))
	}
	
}
